"use client";
import { Inter } from "next/font/google";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import {cartcontext} from '../app/_context/CartContext';
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart,setCart]= useState([]);
  return (
    <ClerkProvider>
     <cartcontext.Provider value={{ cart, setCart }}>
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </cartcontext.Provider>
    </ClerkProvider>
  );
}
